export const UPDATE_DESIRED_CONTRAST_RATIO = 'UPDATE_DESIRED_CONTRAST_RATIO';
export const UPDATE_BACKGROUND_COLOR = 'UPDATE_BACKGROUND_COLOR';
export const UPDATE_FOREGROUND_COLOR = 'UPDATE_FOREGROUND_COLOR';
export const SWITCH_COLORS = 'SWITCH_COLORS';
