export const UPDATE_DESIRED_CONTRAST_RATIO = 'UPDATE_DESIRED_CONTRAST_RATIO';
export const UPDATE_CONSTANT_COLOR = 'UPDATE_CONSTANT_COLOR';
export const UPDATE_COLOR_TO_ADJUST = 'UPDATE_COLOR_TO_ADJUST';
export const SWITCH_COLOR_AND_BACKGROUND_COLOR = 'SWITCH_COLOR_AND_BACKGROUND_COLOR';
