export const UPDATE_ACCESSIBILITY_LEVEL = 'UPDATE_ACCESSIBILITY_LEVEL';
export const UPDATE_BACKGROUND_COLOR = 'UPDATE_BACKGROUND_COLOR';
export const UPDATE_FOREGROUND_COLOR = 'UPDATE_FOREGROUND_COLOR';
export const SWITCH_COLORS = 'SWITCH_COLORS';
