export const UPDATE_ACCESSIBILITY_LEVEL = 'UPDATE_ACCESSIBILITY_LEVEL';
export const UPDATE_BACKGROUND_COLOR_VALUE = 'UPDATE_BACKGROUND_COLOR_VALUE';
export const SWITCH_COLORS = 'SWITCH_COLORS';
export const UPDATE_FOREGROUND_COLOR_VALUE = 'UPDATE_FOREGROUND_COLOR_VALUE';
export const UPDATE_FONT_SIZE = 'UPDATE_FONT_SIZE';
export const TOGGLE_IS_FONT_BOLD = 'TOGGLE_IS_FONT_BOLD';
