export const UPDATE_ACCESSIBILITY_LEVEL = 'UPDATE_ACCESSIBILITY_LEVEL';
export const UPDATE_BACKGROUND_COLOR = 'UPDATE_BACKGROUND_COLOR';
export const SWITCH_COLORS = 'SWITCH_COLORS';
export const UPDATE_FOREGROUND_COLOR = 'UPDATE_FOREGROUND_COLOR';
export const UPDATE_FONT_SIZE = 'UPDATE_FONT_SIZE';
export const TOGGLE_IS_FONT_BOLD = 'TOGGLE_IS_FONT_BOLD';
export const UPDATE_FOCUSED_CHANNEL = 'UPDATE_FOCUSED_CHANNEL';
export const UPDATE_HEADER_COLORS = 'UPDATE_HEADER_COLORS';
