export const UPDATE_COLOR_VALUE = 'UPDATE_COLOR_VALUE';
export const UPDATE_COLOR_HUE = 'UPDATE_COLOR_HUE';
export const UPDATE_COLOR_SATURATION = 'UPDATE_COLOR_SATURATION';
export const UPDATE_COLOR_LIGHTNESS = 'UPDATE_COLOR_LIGHTNESS';
